name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_PAGES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone target repo and copy all files
      run: |
        git clone git@github.com:codeajcf/skills-github-pages.git temp-pages
        rsync -av --exclude=temp-pages --exclude=.git ./ temp-pages/
        cd temp-pages
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-deploy from test repo" || echo "No changes to commit"
        git push origin main  # change to gh-pages if needed
